<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7b4640b0-b73d-4fc1-92e0-1675d70b1e69</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
    <!-- <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.1" /> -->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HospitalManagement.Core\HospitalManagement.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HospitalManagement.Infra\HospitalManagement.Infra.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
    <Folder Include="Models\" />
  </ItemGroup>

</Project>
